version: "3"

services:
  postgresql:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=projeto-catalogodb
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ./backend/db:/bitnami/postgresql
